### ISSUE TITLE
Refactor the lib.rs code into couple of smaller files 

### ISSUE THREAD

**Issue by sahra-karakoc** [graphops/graph-network-substreams#29]
With the recent additions, lib.rs file is almost 800 lines. It contains all the modules related to all the contracts (staking, curation, rewardsManager). It also contains functions that bridge between modules in lib.rs and entityChanges in db.rs, and graph_out. I think it becomes harder and harder to update lib.rs on each change. 

I am thinking of either 
- having one file for each contract, and one for graph_out, or
- having one file for each level of complexity: initial modules, middle map and store modules, bridge functions to db.rs and graph_out.

For the first approach, we either write an initial module for each contract, or have a separate file for the initial modules and then branch after that.

**Comment by juanmardefago** [comment]
One part of the lib.rs file that makes the 1 file per contract approach slightly cumbersome is the map_events (If I recall correctly), which handles the checks agains all the contract addresses supported and wraps the output messages to the event list, but if that can be abstracted away in some way without hurting performance, I think it would be the cleanest solution, and probably easier for expanding the substream afterwards.

**Comment by sahra-karakoc** [comment]
I think I managed to implement what you suggested. Please lmk if you want any further improvements.
